"""Initial database schema

Revision ID: 463073b81d4f
Revises: 
Create Date: 2025-12-06 11:25:11.454830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463073b81d4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cognito_user_pool_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.Enum('TEXT_GENERATION', 'CLASSIFICATION', 'QA', name='tasktype'), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('raw_s3_path', sa.String(length=1024), nullable=False),
    sa.Column('train_s3_path', sa.String(length=1024), nullable=False),
    sa.Column('val_s3_path', sa.String(length=1024), nullable=False),
    sa.Column('test_s3_path', sa.String(length=1024), nullable=False),
    sa.Column('total_samples', sa.Integer(), nullable=False),
    sa.Column('train_samples', sa.Integer(), nullable=False),
    sa.Column('val_samples', sa.Integer(), nullable=False),
    sa.Column('test_samples', sa.Integer(), nullable=False),
    sa.Column('split_seed', sa.Integer(), nullable=False),
    sa.Column('split_ratios', sa.JSON(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fine_tune_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('base_model_id', sa.String(length=255), nullable=False),
    sa.Column('method', sa.Enum('LORA', 'QLORA', name='finetunemethod'), nullable=False),
    sa.Column('adapter_name', sa.String(length=255), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('num_epochs', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('lora_rank', sa.Integer(), nullable=False),
    sa.Column('lora_alpha', sa.Integer(), nullable=False),
    sa.Column('lora_dropout', sa.Float(), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('sagemaker_job_name', sa.String(length=255), nullable=True),
    sa.Column('sagemaker_job_arn', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('final_train_loss', sa.Float(), nullable=True),
    sa.Column('final_val_loss', sa.Float(), nullable=True),
    sa.Column('metrics_s3_path', sa.String(length=1024), nullable=True),
    sa.Column('auto_deploy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adapters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('fine_tune_job_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_model_id', sa.String(length=255), nullable=False),
    sa.Column('s3_path', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fine_tune_job_id'], ['fine_tune_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('adapter_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint_name', sa.String(length=255), nullable=False),
    sa.Column('endpoint_config_name', sa.String(length=255), nullable=True),
    sa.Column('endpoint_arn', sa.String(length=512), nullable=True),
    sa.Column('instance_type', sa.String(length=50), nullable=False),
    sa.Column('instance_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATING', 'ACTIVE', 'UPDATING', 'DELETING', 'DELETED', 'FAILED', name='deploymentstatus'), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['adapter_id'], ['adapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployments')
    op.drop_table('adapters')
    op.drop_table('fine_tune_jobs')
    op.drop_table('datasets')
    op.drop_table('tenants')
    # ### end Alembic commands ###
